name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      release:
        description: Input something to release an automated build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: latest
          no-cache: true
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - name: Install dependencies
        run: |
          npm install -g terser
          pip install donna25519==0.1.* ed25519==1.*
      - name: Build wasm-c25519
        run: |
          node build.js
          ls -l dist
      - name: Test
        run: node test-standard.js
      - name: Benchmark
        if: ${{ !github.event.inputs.release }}
        run: |
          python test-massive-generate.py
          node test-massive.js
      - name: Upload result
        if: ${{ !github.event.inputs.release }}
        uses: actions/upload-artifact@v2
        with:
          name: wasm-c25519
          path: dist/
      - name: Release automated build
        if: ${{ github.event.inputs.release }}
        run: |
          export BUILD_TIME=$(date +%Y%m%d-%H%I%S)
          echo "release_name=Automated build $BUILD_TIME" >> $GITHUB_ENV
          echo "tag_name=autobuild-$BUILD_TIME" >> $GITHUB_ENV
          echo "file_name=autobuild-$BUILD_TIME.zip" >> $GITHUB_ENV
          cd dist
          zip -9 -r "../autobuild-$BUILD_TIME.zip" .
          cd ..
      - uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.release }}
        with:
          name: ${{ env.release_name }}
          tag_name: ${{ env.tag_name }}
          prerelease: true
          files: ${{ env.file_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
